autoInstallPeers: true
catalogMode: prefer
cleanupUnusedCatalogs: true
engineStrict: true
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
verifyDepsBeforeRun: prompt

packages:
  - docs
  - example/*
  - packages/*

allowBuilds:
  esbuild: true
  simple-git-hooks: true
